name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Build and push Docker image?'
        required: true
        type: choice
        options:
        - 'Yes'
        - 'No'
        default: 'No'

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    if: github.event.inputs.build == 'Yes'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checking OS information
        run: |
          lscpu
          uname -a
          df -h

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Tag and push latest image
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:${{ github.sha }} ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:latest
